-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 10:43:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bands` (
  `idBands` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `integrants` INT NULL,
  PRIMARY KEY (`idBands`),
  UNIQUE INDEX `idBands_UNIQUE` (`idBands` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Concert` (
  `idConcert` INT NOT NULL AUTO_INCREMENT,
  `durationMin` FLOAT NOT NULL,
  `Bands_idBands` INT NOT NULL,
  PRIMARY KEY (`idConcert`),
  UNIQUE INDEX `idConcert_UNIQUE` (`idConcert` ASC) VISIBLE,
  INDEX `fk_Concert_Bands_idx` (`Bands_idBands` ASC) VISIBLE,
  CONSTRAINT `fk_Concert_Bands`
    FOREIGN KEY (`Bands_idBands`)
    REFERENCES `mydb`.`Bands` (`idBands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ScenarioRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ScenarioRoom` (
  `idScenario` INT NOT NULL AUTO_INCREMENT,
  `capability` INT NOT NULL,
  `Concert_idConcert` INT NOT NULL,
  PRIMARY KEY (`idScenario`),
  UNIQUE INDEX `idScenario_UNIQUE` (`idScenario` ASC) VISIBLE,
  INDEX `fk_ScenarioRoom_Concert1_idx` (`Concert_idConcert` ASC) VISIBLE,
  CONSTRAINT `fk_ScenarioRoom_Concert1`
    FOREIGN KEY (`Concert_idConcert`)
    REFERENCES `mydb`.`Concert` (`idConcert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seats` (
  `idSeats` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `reserved` TINYINT NULL DEFAULT 0,
  `Scenario_idScenario` INT NOT NULL,
  PRIMARY KEY (`idSeats`),
  UNIQUE INDEX `idSeats_UNIQUE` (`idSeats` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_Seats_Scenario1_idx` (`Scenario_idScenario` ASC) VISIBLE,
  CONSTRAINT `fk_Seats_Scenario1`
    FOREIGN KEY (`Scenario_idScenario`)
    REFERENCES `mydb`.`ScenarioRoom` (`idScenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `idTickets` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NULL,
  `Seats_number` INT NOT NULL,
  `Concert_idConcert` INT NOT NULL,
  PRIMARY KEY (`idTickets`, `Concert_idConcert`),
  UNIQUE INDEX `idTickets_UNIQUE` (`idTickets` ASC) VISIBLE,
  INDEX `fk_Tickets_Seats1_idx` (`Seats_number` ASC) VISIBLE,
  INDEX `fk_Tickets_Concert1_idx` (`Concert_idConcert` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Seats1`
    FOREIGN KEY (`Seats_number`)
    REFERENCES `mydb`.`Seats` (`idSeats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Concert1`
    FOREIGN KEY (`Concert_idConcert`)
    REFERENCES `mydb`.`Concert` (`idConcert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audience` (
  `idAudience` INT NOT NULL AUTO_INCREMENT,
  `Person_idPerson` INT NOT NULL,
  `Tickets_idTickets` INT NOT NULL,
  PRIMARY KEY (`idAudience`),
  UNIQUE INDEX `idAudience_UNIQUE` (`idAudience` ASC) VISIBLE,
  INDEX `fk_Audience_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  INDEX `fk_Audience_Tickets1_idx` (`Tickets_idTickets` ASC) VISIBLE,
  CONSTRAINT `fk_Audience_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `mydb`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musician` (
  `idMusician` INT NOT NULL AUTO_INCREMENT,
  `Person_idPerson` INT NOT NULL,
  `Bands_idBands` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  INDEX `fk_Person_has_Bands_Bands1_idx` (`Bands_idBands` ASC) VISIBLE,
  INDEX `fk_Person_has_Bands_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  PRIMARY KEY (`idMusician`),
  UNIQUE INDEX `idMusician_UNIQUE` (`idMusician` ASC) VISIBLE,
  CONSTRAINT `fk_Person_has_Bands_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Bands_Bands1`
    FOREIGN KEY (`Bands_idBands`)
    REFERENCES `mydb`.`Bands` (`idBands`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CleanService`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CleanService` (
  `idCleanService` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `time` FLOAT NULL,
  PRIMARY KEY (`idCleanService`),
  UNIQUE INDEX `idCleanService_UNIQUE` (`idCleanService` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CleaningScenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CleaningScenario` (
  `idCleaning` INT NOT NULL AUTO_INCREMENT,
  `ScenarioRoom_idScenario` INT NOT NULL,
  `CleanService_idCleanService` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`idCleaning`),
  INDEX `fk_ScenarioRoom_has_CleanService_CleanService1_idx` (`CleanService_idCleanService` ASC) VISIBLE,
  INDEX `fk_ScenarioRoom_has_CleanService_ScenarioRoom1_idx` (`ScenarioRoom_idScenario` ASC) VISIBLE,
  UNIQUE INDEX `CleaningScenariocol_UNIQUE` (`idCleaning` ASC) VISIBLE,
  CONSTRAINT `fk_ScenarioRoom_has_CleanService_ScenarioRoom1`
    FOREIGN KEY (`ScenarioRoom_idScenario`)
    REFERENCES `mydb`.`ScenarioRoom` (`idScenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ScenarioRoom_has_CleanService_CleanService1`
    FOREIGN KEY (`CleanService_idCleanService`)
    REFERENCES `mydb`.`CleanService` (`idCleanService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
